### ISSUE TITLE
"<new>" header required

### ISSUE THREAD

**Issue by squidcc** [diasurgical/riivaaja#13]
Can I get the header file for "new" added to the docker image, msgcmd.cpp requires the placement new operator and it's not usable without including that header.
It may have dependencies on other headers (likely "exception") but I can't say for sure.

**Comment by AJenbo** [comment]
@squidcc can you give me a code sample or branch to test it with so that I can track down all needed files?

**Comment by squidcc** [comment]
You can try https://github.com/squidcc/devilution/tree/msgcmd or probably just put `#include <new>` in any .cpp file.

**Comment by AJenbo** [comment]
I seam to be getting an error for a missing file even when using the full include folder, seams a bit odd since it's required by the file in the include folder:
`VS6/VC98/Include\new(9) : fatal error C1083: Cannot open include file: 'exception': No such file or directory`
Any ideas where i should get that file from?

**Comment by squidcc** [comment]
That should not be happening. Was VC6 actually installed (using the setup program) or were the files copied directly from an ISO/CAB files?

**Comment by squidcc** [comment]
I figured out what's going on; the original install media didn't fully support long filenames, so standard headers like `<exception>`, `<algorithm>`, `<strstream>` etc. were given shorter 8.3 compliant filenames on the original disks and renamed by setup.exe as they were installed. There should be a map of short->long filenames in an .inf file in the \SETUP directory. In this case XCEPTION is the file that needs renaming to "exception".

If that gets `<new>` working can you add `<typeinfo>` as well? VC6 doesn't strictly need it to build the msgcmd code but it looks like the mingw builds are failing without it (and I'd rather not do an `#ifdef _MSVC` to conditionally include it).

**Comment by AJenbo** [comment]
Thanks that is really helpful, I'm a bit limited here with not having an system willing to fully compleat the original install process.

Adding <typeinfo> woudn't help mingw as it doesn't run inside Riivaaja (specific for VC5+VC6 building)

**Comment by squidcc** [comment]
> Adding woudn't help mingw as it doesn't run inside Riivaaja (specific for VC5+VC6 building)

I mean I need to add `#include <typeinfo>` to make mingw builds work (otherwise they complain about using typeid() ), so I need that header to exist for VC6 too.

**Comment by AJenbo** [comment]
Ok so the 4 only files that I needed to add where
`new`, `exception`, `eh.h` and `typeinfo`

the game compile and runs, but i get the following errors during the compile:
```
msgcmd.cpp
0009:err:msvcrt:demangle_datatype Unknown type @
0009:err:msvcrt:demangle_datatype Unknown type @
```
The only line i have commented out is:
`static __inline void* operator new(size_t count, void* _p) { return _p; }`
Just to be sure could you prepare the branch to where it expects exverything to be implace.

You also mentioned needing additional flags, feel free to add that to the make file (do you expect this could affect other code?)

**Comment by squidcc** [comment]
https://github.com/squidcc/devilution/tree/msgcmd2 is ready to build with added headers, it already builds successfully with mingw.

**Comment by AJenbo** [comment]
The new dependencies should now be in place

**Comment by squidcc** [comment]
Building without "-e MAKE_BUILD=pdb" now fails because the VC5 linker can't be found ("/root/DevStudio_5.10/VC/bin/link.exe").

**Comment by AJenbo** [comment]
Should be fixed now

**Comment by AJenbo** [comment]
This should also have been fixed now
