### ISSUE TITLE
[question] Hellfire - command for compiling

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/riivaaja#14]
@AJenbo, @qndel, I can not use the following command for compiling the hellfire branch.
"docker run --rm -v $(pwd):/root/devilution -e MAKE_BUILD=pdb diasurgical/riivaaja"
Is an additional parameter required for compiling the hellfire executable?
Thank you much in advance.

**Comment by Chance4us** [comment]
Following seems to work.
docker run --rm -v $(pwd):/root/devilution -e MAKE_BUILD=pdb -e HELLFIRE=1 diasurgical/riivaaja

**Comment by qndel** [comment]
I wouldn't know, I'm not using docker ;)

**Comment by AJenbo** [comment]
your 18 hours late :o

**Comment by qndel** [comment]
I'm never late ;)
